global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'nakama'
    static_configs:
      - targets: ['nakama:7350']

  - job_name: 'world'
    static_configs:
      - targets: ['world:8090']
